
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NAO TELEINFORMATICA
 */
public class FEstadistica extends javax.swing.JFrame {

    ArrayList<ArrayList<String>> datos = new ArrayList();
    ArrayList<String> series = new ArrayList();

    GraficaXY chart;
    Conexion cnx = new Conexion();

    String empleado = "";

    public FEstadistica() {
        initComponents();

        setLocationRelativeTo(this);

        if (cnx.conectar("localhost", "store", "root", "") == 0) {
            JOptionPane.showMessageDialog(this, "ERROR DE CONEXION");
            System.exit(0);
        }

        cnx.seleccionar("SELECT folio FROM pedidos ORDER BY folio", CBFolio);

    }

    void asignarEmpleado(String user) {
        empleado = user;
        LUsuario.setText("Usuario: " + empleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LUsuario = new javax.swing.JLabel();
        PGrafica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TQuery = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        CBFolio = new javax.swing.JComboBox<>();
        BBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        DCInicial = new com.toedter.calendar.JDateChooser();
        DCFinal = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BGeneral = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        BDiario = new javax.swing.JButton();
        BSemana = new javax.swing.JButton();
        BMensual = new javax.swing.JButton();
        BAnual = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        BReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NIVELES DE GLUCOSA");

        jPanel1.setBackground(new java.awt.Color(97, 187, 255));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Graficación de niveles de glucosa");

        jPanel2.setBackground(new java.awt.Color(168, 86, 188));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(LUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        PGrafica.setBackground(new java.awt.Color(153, 153, 153));
        PGrafica.setLayout(new java.awt.GridLayout(1, 0));

        TQuery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TQuery);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        CBFolio.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        CBFolio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBFolio.setMaximumSize(new java.awt.Dimension(200, 50));
        CBFolio.setMinimumSize(new java.awt.Dimension(200, 50));
        CBFolio.setPreferredSize(new java.awt.Dimension(200, 50));
        CBFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFolioActionPerformed(evt);
            }
        });
        jToolBar1.add(CBFolio);

        BBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VEKKA/src/img/Search(1).png"))); // NOI18N
        BBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BBuscar.setFocusable(false);
        BBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(BBuscar);
        jToolBar1.add(jSeparator1);

        DCInicial.setDate(new Date(122,10,1));
        jToolBar1.add(DCInicial);

        DCFinal.setDate(new Date(122,10,30));
        jToolBar1.add(DCFinal);
        jToolBar1.add(jSeparator2);

        BGeneral.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        BGeneral.setText("GENERAL");
        BGeneral.setToolTipText("");
        BGeneral.setFocusable(false);
        BGeneral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BGeneral.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGeneralActionPerformed(evt);
            }
        });
        jToolBar1.add(BGeneral);
        jToolBar1.add(jSeparator3);

        BDiario.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        BDiario.setText("DIARIO");
        BDiario.setFocusable(false);
        BDiario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BDiario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDiarioActionPerformed(evt);
            }
        });
        jToolBar1.add(BDiario);

        BSemana.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        BSemana.setText("SEMANAL");
        BSemana.setFocusable(false);
        BSemana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BSemana.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSemanaActionPerformed(evt);
            }
        });
        jToolBar1.add(BSemana);

        BMensual.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        BMensual.setText("MENSUAL");
        BMensual.setFocusable(false);
        BMensual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BMensual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMensualActionPerformed(evt);
            }
        });
        jToolBar1.add(BMensual);

        BAnual.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        BAnual.setText("ANUAL");
        BAnual.setFocusable(false);
        BAnual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAnual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnualActionPerformed(evt);
            }
        });
        jToolBar1.add(BAnual);
        jToolBar1.add(jSeparator4);

        BReporte.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        BReporte.setText("REPORTE");
        BReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReporteActionPerformed(evt);
            }
        });
        jToolBar1.add(BReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(PGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGeneralActionPerformed
        String folio = CBFolio.getSelectedItem().toString();
        Date fi = DCInicial.getDate();
        Date ff = DCFinal.getDate();
        String fini = cnx.toSQL(fi);
        String ffin = cnx.toSQL(ff);

        String ventas = "SELECT folio, SUM(cantidadp*preciod) AS Total, SUM(cantidadp*(preciod-preciobase)) AS Ganancias "
                + "FROM detalles, pedidos, productos "
                + "WHERE folio = pedidos_folio AND idproductos=productos_idproductos AND "
                + "fecha BETWEEN '" + fini + "' AND '" + ffin + "' "
                + "GROUP BY folio";

        cnx.entablar(ventas, TQuery);

        series.clear();
        series.add("Ventas");
        series.add("Ganancias");
        datos = cnx.consultar(ventas);

        PGrafica.removeAll();
        chart = new GraficaXY("Ventas", "Pedidos", "Total", series, datos);
        PGrafica.add(chart.chartPanel);
        PGrafica.updateUI();
    }//GEN-LAST:event_BGeneralActionPerformed

    private void CBFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFolioActionPerformed

    private void BMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMensualActionPerformed
        String curp = CBFolio.getSelectedItem().toString();
        Date fi = DCInicial.getDate();
        Date ff = DCFinal.getDate();
        String fini = cnx.toSQL(fi);
        String ffin = cnx.toSQL(ff);

        String suggar = "SELECT MONTH(fecha) AS tiempo, AVG(nvl_glucosa) AS glucosa "
                + "FROM mediciones "
                + "WHERE pacientes_curp = '" + curp + "' "
                + "AND fecha BETWEEN '" + fini + "' AND '" + ffin + "' "
                + "GROUP BY MONTH(fecha)";

        cnx.entablar(suggar, TQuery);

        series.clear();
        series.add("Glucosa");
        datos = cnx.consultar(suggar);

        PGrafica.removeAll();
        chart = new GraficaXY("Mediciones", "Fechas", "Nivel", series, datos);
        PGrafica.add(chart.chartPanel);
        PGrafica.updateUI();
    }//GEN-LAST:event_BMensualActionPerformed

    private void BSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSemanaActionPerformed
        String curp = CBFolio.getSelectedItem().toString();
        Date fi = DCInicial.getDate();
        Date ff = DCFinal.getDate();
        String fini = cnx.toSQL(fi);
        String ffin = cnx.toSQL(ff);

        String suggar = "SELECT WEEK(fecha) AS tiempo, AVG(nvl_glucosa) AS glucosa "
                + "FROM mediciones "
                + "WHERE pacientes_curp = '" + curp + "' "
                + "AND fecha BETWEEN '" + fini + "' AND '" + ffin + "' "
                + "GROUP BY WEEK(fecha)";

        cnx.entablar(suggar, TQuery);

        series.clear();
        series.add("Glucosa");
        datos = cnx.consultar(suggar);

        PGrafica.removeAll();
        chart = new GraficaXY("Mediciones", "Fechas", "Nivel", series, datos);
        PGrafica.add(chart.chartPanel);
        PGrafica.updateUI();
    }//GEN-LAST:event_BSemanaActionPerformed

    private void BDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDiarioActionPerformed
        String curp = CBFolio.getSelectedItem().toString();
        Date fi = DCInicial.getDate();
        Date ff = DCFinal.getDate();
        String fini = cnx.toSQL(fi);
        String ffin = cnx.toSQL(ff);

        String suggar = "SELECT CONCAT(DAY(fecha),'-',MONTH(fecha)) AS tiempo, AVG(nvl_glucosa) AS glucosa "
                + "FROM mediciones "
                + "WHERE pacientes_curp = '" + curp + "' "
                + "AND fecha BETWEEN '" + fini + "' AND '" + ffin + "' "
                + "GROUP BY DAY(fecha), MONTH(fecha)";

        cnx.entablar(suggar, TQuery);

        series.clear();
        series.add("Glucosa");
        datos = cnx.consultar(suggar);

        PGrafica.removeAll();
        chart = new GraficaXY("Mediciones", "Fechas", "Nivel", series, datos);
        PGrafica.add(chart.chartPanel);
        PGrafica.updateUI();
    }//GEN-LAST:event_BDiarioActionPerformed

    private void BAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnualActionPerformed
        String curp = CBFolio.getSelectedItem().toString();
        Date fi = DCInicial.getDate();
        Date ff = DCFinal.getDate();
        String fini = cnx.toSQL(fi);
        String ffin = cnx.toSQL(ff);

        String suggar = "SELECT YEAR(fecha) AS tiempo, AVG(nvl_glucosa) AS glucosa "
                + "FROM mediciones "
                + "WHERE pacientes_curp = '" + curp + "' "
                + "AND fecha BETWEEN '" + fini + "' AND '" + ffin + "' "
                + "GROUP BY YEAR(fecha)";

        cnx.entablar(suggar, TQuery);

        series.clear();
        series.add("Glucosa");
        datos = cnx.consultar(suggar);

        PGrafica.removeAll();
        chart = new GraficaXY("Mediciones", "Fechas", "Nivel", series, datos);
        PGrafica.add(chart.chartPanel);
        PGrafica.updateUI();
    }//GEN-LAST:event_BAnualActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        

    }//GEN-LAST:event_BBuscarActionPerformed

    private void BReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReporteActionPerformed
        String curp = CBFolio.getSelectedItem().toString();
        Date fini = DCInicial.getDate();
        Date ffin = DCFinal.getDate();

        String reporte = System.getProperty("user.dir") + "/glucemia.jasper";

        Map parametros = new HashMap();
        parametros.put("curp", curp);
        parametros.put("fini", fini);
        parametros.put("ffin", ffin);
        parametros.put("Periodo", "nada");

        cnx.ejecutarReporte(reporte, parametros);
    }//GEN-LAST:event_BReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEstadistica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEstadistica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEstadistica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEstadistica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEstadistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnual;
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BDiario;
    private javax.swing.JButton BGeneral;
    private javax.swing.JButton BMensual;
    private javax.swing.JButton BReporte;
    private javax.swing.JButton BSemana;
    public javax.swing.JComboBox<String> CBFolio;
    private com.toedter.calendar.JDateChooser DCFinal;
    private com.toedter.calendar.JDateChooser DCInicial;
    private javax.swing.JLabel LUsuario;
    private javax.swing.JPanel PGrafica;
    private javax.swing.JTable TQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
