
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author drlias
 */
public class JPEmpleados extends javax.swing.JPanel {

    Conexion cnx;

    public JPEmpleados(Conexion cnx) {
        initComponents();

        TEmpleados.setRowHeight(50);

        String sql = "SELECT * FROM empleados";
        cnx.entablar(sql, TEmpleados);

        this.cnx = cnx;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEmpleados = new javax.swing.JTable();
        BReporte = new javax.swing.JButton();
        BActu = new javax.swing.JButton();
        TFEmpleados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TFCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFPuesto = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Empleados");

        BRegistrar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        BRegistrar.setText("REGISTRAR");
        BRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrarActionPerformed(evt);
            }
        });

        TEmpleados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Teléfono", "Puesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TEmpleados.setAlignmentX(1.0F);
        TEmpleados.setAlignmentY(1.0F);
        TEmpleados.setRowMargin(0);
        TEmpleados.setSelectionBackground(new java.awt.Color(204, 255, 204));
        TEmpleados.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TEmpleadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TEmpleados);

        BReporte.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        BReporte.setText("REPORTE");
        BReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReporteActionPerformed(evt);
            }
        });

        BActu.setText("ACTUALIZAR");
        BActu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActuActionPerformed(evt);
            }
        });

        TFEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEmpleadosKeyPressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search(1).png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BBorrar.setText("BORRAR");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Complete los datos correspondientes");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CODIGO:");

        TFCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");

        TFNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("TELÉFONO:");

        TFTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("PUESTO:");

        TFPuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFCodigo)
                    .addComponent(TFNom)
                    .addComponent(TFTel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 204, Short.MAX_VALUE))
                    .addComponent(TFPuesto))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TFEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BRegistrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BActu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BReporte))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TFEmpleados))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRegistrar)
                    .addComponent(BActu)
                    .addComponent(BBorrar)
                    .addComponent(BReporte))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrarActionPerformed
        String id = TFCodigo.getText();
        String nom = TFNom.getText();
        String tel = TFTel.getText();
        String pue = TFPuesto.getText();

        Empleados em = new Empleados(id, nom, tel, pue);

        if (id.equals("")) {
            JOptionPane.showMessageDialog(this, "Hubo un error, intente de nuevo");
        } else if (em.insertar(cnx) == 1) {
            JOptionPane.showMessageDialog(this, "Empleado agregado");
            cnx.entablar("SELECT * FROM empleados", TEmpleados);

            TFCodigo.setText("");
            TFNom.setText("");
            TFTel.setText("");
            TFPuesto.setText("");

        }
    }//GEN-LAST:event_BRegistrarActionPerformed

    private void TEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMousePressed
        int ren = TEmpleados.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) TEmpleados.getModel();

        if (ren >= 0) {
            TFCodigo.setText(modelo.getValueAt(ren, 0).toString());
            TFNom.setText(modelo.getValueAt(ren, 1).toString());
            TFTel.setText(modelo.getValueAt(ren, 2).toString());
            TFPuesto.setText(modelo.getValueAt(ren, 3).toString());

        }
    }//GEN-LAST:event_TEmpleadosMousePressed

    private void BActuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActuActionPerformed
        String id = TFCodigo.getText();
        String nom = TFNom.getText();
        String tel = TFTel.getText();
        String pue = TFPuesto.getText();

        Empleados cl = new Empleados(id, nom, tel, pue);
        if (cl.actualizar(cnx) == 1) {
            String sql = "SELECT * FROM empleados";
            JOptionPane.showMessageDialog(this, "Datos Actualizados");
            cnx.entablar(sql, TEmpleados);

            TFCodigo.setText("");
            TFNom.setText("");
            TFTel.setText("");
            TFPuesto.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar");
        }
    }//GEN-LAST:event_BActuActionPerformed

    private void TFEmpleadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEmpleadosKeyPressed
        String name = TFEmpleados.getText();
        String sql = "SELECT * FROM empleados WHERE nombree LIKE '%" + name + "%'";
        cnx.entablar(sql, TEmpleados);
    }//GEN-LAST:event_TFEmpleadosKeyPressed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        int rensel = TEmpleados.getSelectedRow();
        if (rensel > -1) {
            DefaultTableModel datos = (DefaultTableModel) TEmpleados.getModel();
            String codigo = datos.getValueAt(rensel, 0).toString();

            String id = TFCodigo.getText();
            String nom = TFNom.getText();
            String tel = TFTel.getText();
            String pue = TFPuesto.getText();

            Empleados cl = new Empleados(id, nom, tel, pue);
            if (cl.remover(cnx) == 1) {
                String sql = "SELECT * FROM empleados";
                JOptionPane.showMessageDialog(this, "Empleado Borrado");
                cnx.entablar(sql, TEmpleados);

                TFCodigo.setText("");
                TFNom.setText("");
                TFTel.setText("");
                TFPuesto.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Primero selecciona al empleado de la Tabla");

        }
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReporteActionPerformed
        String cla = TFCodigo.getText();
        String reporte = System.getProperty("user.dir") + "/empleados.jasper";

        Map parametros = new HashMap();
        parametros.put("clavePel", cla);

        cnx.ejecutarReporte(reporte, parametros);
    }//GEN-LAST:event_BReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActu;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BRegistrar;
    private javax.swing.JButton BReporte;
    private javax.swing.JTable TEmpleados;
    private javax.swing.JTextField TFCodigo;
    private javax.swing.JTextField TFEmpleados;
    private javax.swing.JTextField TFNom;
    private javax.swing.JTextField TFPuesto;
    private javax.swing.JTextField TFTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
